# Generated by Django 4.0.1 on 2022-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(blank=True, choices=[('Dublin', 'Dublin'), ('Outside Dublin', 'OutSide Dublin')], max_length=20, null=True),
        ),
    ]
