# Generated by Django 4.0.1 on 2022-09-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_area_alter_listing_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(blank=True, choices=[('Dublin', 'Dublin'), ('Outside Dublin', 'OutSide Dublin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_status',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rental_frequency',
            field=models.CharField(blank=True, choices=[('Month', 'Month'), ('Week', 'Week'), ('Day', 'Day')], max_length=20, null=True),
        ),
    ]
